### PR TITLE
Reddit started hosting .vtt files and it causes problems

### PR DESCRIPTION
**Pull request by Bagdaja**
Reddit started hosting .vtt files and they can be mix up the video qualities. I made it so they are ignored. it could be fixed by just forcing the DASH urls to end with .mp4 but I simply made them ignore .vtt

### CODE REVIEW

**Comment by elmoiv** [comment]
Thank you for your contribution.

Please post a reddit post url that contains this vtt files.

**Comment by vinmorel** [comment]
`https://v.redd.it/6aojgdb15ihb1`

**Review by elmoiv — CHANGES_REQUESTED** [review]
You copied old changelog and forgot to update it with the new url:

Just change it to:
https://github.com/elmoiv/redvid/pull/33/

**Comment by Bagdaja** [comment]
Done!

**Comment by elmoiv** [comment]
Thank you

**Review by elmoiv — APPROVED** [review]

**Pull request merged**
